version: '3'

services:
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: jira
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: JiraRush
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
#      DB_URL: jdbc:postgresql://database:5432/jira
#      DB_HOST: database
#      DB_PORT: 5432
      DB_NAME: jira
      DB_USERNAME: jira
      DB_PASSWORD: JiraRush
#    restart: always
    links:
      - database

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 80:80
    depends_on:
      - server
    restart: always

volumes:
  postgres-data: